[package]
name = "shakmat-engine"
version = "0.1.0"
edition = "2021"
authors = ["https://github.com/agubelu/"]

[dependencies]
rand = "0.8.4"
rustc-hash = "1.1.0"
shakmat-core = { path = "../shakmat-core" }