on: [push]

name: CI

jobs:
  test:
    name: Shakmat-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo test --release -- --test-threads=1
#     we set test-threads=1 to avoid running tests in parallel,
#     since each test uses all available CPU cores